version: '3.8'

services:
  # Flask app service
  my-simple-blog:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  # Prometheus service
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana service
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
